src/application.rs
The `User` and `Service` modules do not implement all the traits that they should yet. That's why I only added docs for the `Application` module.
=> Add docs for the Application module

src/user.rs
Same as we did in https://github.com/unleashed/threescalers/commit/ce5dc985e676e32f940da959b5409a52b490b14b for `Application`.
=> Avoid stringly types in User module by implementing several traits

src/service.rs
Similar to #5 but this time for the Service module.
@unleashed, we might want to divide these modules in the future. They're growing fast with all those trait implementations.
=> Avoid stringly types in Service module by implementing several traits

src/request.rs
Simple PR. I was writing some tests and noticed that we don't have any getters in `Request`.
=> Add getters for Request

tests/apicall.rs
@unleashed I have added an integration test. We'll need to write many tests to cover all the possible combinations of `service_id`, `app_id`, `user_id`, etc. However, before writing all of them, I'd like to agree on the structure we should follow. As you can see, the test I've included in this PR is a bit verbose, but I think it's easy to follow what's being tested. I guess that using macros, we could make the tests a little less verbose, but I don't think it's worth it at this point. Let me know what you think.
=> Add initial integration tests

tests/apicall.rs
I've added integration tests for all the possible combinations of Authorize requests. In the process, I've realized that our code has some bugs. I've marked with `#[ignore]` the tests that don't pass so we know what cases need to be fixed.
=> Add integration tests for Authorize requests

.travis.yml
This PR fixes the error we are getting in Travis:
```
Package libbfd-dev is a virtual package provided by:
binutils-2.26-dev 2.26.1-1ubuntu1~14.04
binutils-dev 2.24-5ubuntu14.2
E: Package 'libbfd-dev' has no installation candidate
```
=> Fix travis build by specifying binutils-dev as a dependency instead of libbfd-dev

.travis.yml, Cargo.toml, src/apicall.rs, src/application.rs, src/service.rs, src/user.rs, tests/apicall.rs
This is the result of running `cargo fix --edition`, adding the proper flag
to Cargo.toml and removing some superfluous syntax.
=> misc: update to Rust 2018 edition

src/lib.rs, src/usage.rs
Usage is needed for `authorize` and `authrep` calls.
=> Add usage module

src/application.rs
This PR makes the ergonomics of `Application` a bit better by
using the `From` trait.
The reason is that `Into<T>` does not have a corresponding trait
automatically defined as `From<U>`. And in turn, the reason for this
is that, besides avoiding a circular reference that would conflict
with existing `From` impls (and without specialization that'd be an
error), it is not always possible to define a `From<U>` trait due to
coherence rules, but you can always define an `Into<T>` trait.
At https://doc.rust-lang.org/std/convert/trait.Into.html you can see
the paragraph below:
Library authors should not directly implement this trait, but should
prefer implementing the `From` trait, which offers greater flexibility
and provides an equivalent Into implementation for free, thanks to a
blanket …
=> application: use From trait instead of Into

.appveyor.yml, .travis.yml, ci/install.sh
Update the travis & appveyor templates + ci scripts to latest master in trust.
Note that tests might fail while I tune this.
And also:
* With the update avoids installing rust twice in newer images from Travis.
* Ensures rustfmt is installed via rustup.
* Correctly limits checks with clippy and rustfmt to nightly.
* Tests the two windows toolchains in appveyor.
=> Update trust CI system

src/errors.rs, tests/api_call.rs
These were either left-overs or required back in the time where this library moved to the 2018 edition, and no longer required (error_chain ones).
=> Remove warnings about unused imports

Cargo.toml
This is required to be able to publish the library on crates.io. The idea is to keep these as relaxed as possible while trying to ensure compatibility.
=> Cargo.toml: specify caret reqs in dependencies for publication

.travis.yml, Cargo.toml, build.rs, src/http/parameters.rs, src/lib.rs
We generate the docs on master and coverage with stable, so let's enable it again.
Update: now we set a `nightly` feature flag to detect nightly compilers and run benchmarks (since they are only available on nightly and require enabling a feature flag and importing a crate).
=> Instrument travis phases and enable testing on stable

.travis.yml, Cargo.toml, README.md, bors.toml
This changes repo slugs, configures bors and excludes CI infrastructure from the crate package.
=> Migrate to 3scale-rs

Cargo.toml
Currently cargo will warn about some files being excluded (and we want them excluded!). Silence that warning by using the recommended pattern.
=> Cargo.toml: remove cargo build warnings due to new matching of excludes

Cargo.toml, examples/reqwest-report.rs
This is an example using the library with Reqwest. Preferably merge after #36.
To run this example you'll need to:
> $ cargo run --example reqwest-report --features reqwest-sync
Alternatively you can pass --all-features instead of the exact features required by the example.
=> Reqwest example

Cargo.toml, src/lib.rs, src/response.rs
This is a draft so far, just to test the deserialization of XML bodies. The fields are currently declared as `String`s but period data should be deserialized into proper timestamps. Other things like headers would be supported via `Response` objects from similar libraries as those supported by `Request`s.
=> response: add a module for basic parsing of XML requests

src/response.rs
Ref: https://github.com/3scale-rs/threescalers/pull/27#discussion_r300827579
=> Explain call to next_key() even when the key is not needed

src/http/request/reqwest.rs
There is already a String containing the body that is being consumed
in this function, so rather than cloning a body String that will be
deallocated, just move the String into reqwest.
=> reqwest: avoid cloning a request's body unnecessarily

.cargo/config
This will allow users to quickly run specific examples without
having to look up which specific flags to use.
=> cargo: config for an alias for the reqwest example

.cargo/config, Cargo.toml, examples/curl-report.rs, src/http/request.rs, src/http/request/curl.rs
This introduces libcurl support with the `curl::Easy` client. We'll probably also provide support for the `Easy2` client too in the future at least.
Note that the fact we create our own type is needed to enable usage of the `transfer()` method in the client when posting data. Depending on how usage progresses we might need further changes.
We also add an example which currently mostly copies the Reqwest one.
=> libcurl support

.travis.yml
They were only being flagged in a subshell due to a brainfart.
(btw: some `Default` implementations being suggested by clippy)
=> .travis.yml: actually enable clippy and rustfmt

src/extensions.rs, src/response.rs
This adds some useful methods to `MetricsHierarchy` to allow doing useful work with it.
(while at it we also fix a couple of clippy suggestions, including one about `Extensions` which is essentially the same type as `MetricsHierarchy`)
=> Add minimal behaviour to MetricsHierarchy

examples/curl-report.rs, examples/reqwest-report.rs, src/http/request.rs, src/http/request/curl.rs, src/http/request/http.rs, src/http/request/reqwest.rs, src/lib.rs
The previous trait, while working, had some ergonomic issues. For
example, it did require in some cases for the implementation to
create the client, and in others it required a mutable reference or
a move in the generic parameters.
It also used a free-standing function to do this, and in some cases
it required non-obvious types to call it on.
The new trait feels more natural while maintaining the flexibility,
in which we now require a client to exist before configuring our
request to be sent off. This change should convey that impls will no
longer create the clients, but just set them up with whatever is
required to perform a call.
=> Refactor FromRequest to make it more ergonomic and convey actual meaning

src/http/request/curl/easy2.rs, src/lib.rs
The only other relevant changes are:
- Adding a missing `Clone` trait.
- Stop making `ToParams` public (only crate-public).
This is a draft PR because these docs would benefit from a bit more work on them (ie. specifying structs as [`TheStruct`] and similar, and maybe some extra docs for the 0.2 release.
Edit: just going to leave it as is to have the 0.2 release done.
=> Convert some comments to docs

.travis.yml
The nightly one can vary wildly with regressions and turn PR's red
needing short-lived changes that in turn will fail when the
regressions are fixed. So use rustfmt as shipped with stable.
=> .travis.yml: use rustfmt from the stable toolchain only

.travis.yml, src/lib.rs, src/response.rs, src/timestamp.rs
This is related to API errors PR we are working on but does not depend on it.
Here we add a bit of error handling for cases in which the parsing of dates from responses fail, and updates the `Timestamp` type to use `i64` for conversions (while using `TryFrom` too for safety) thus being allowed to represent wide enough offsets from the Unix epoch in both directions.
=> Timestamp & DateTime fixes

src/lib.rs
It is stabilized for 1.41.0. It currently generates a warning in nightly.
=> src/lib: feature(never_type) no longer required in nightly

examples/curl-easy-report.rs, examples/curl-easy2-report.rs, examples/reqwest-report.rs
Such calls will likely create by-value iterators in the future, and
raise warnings in 1.41.0+.
See issue 66145 in rust-lang/rust.
=> examples: use [T]::iter() rather than [T]::into_iter()

.travis.yml, ci/dependency-decisions.yml
Fix issue with a new dependency in the tree that includes another variation of ASL2 and MIT. While at it upgrade to license finder 6.
=> Update to LF 6 and fix new instance of unrecognised Apache2/MIT title

src/http/request/curl/easy.rs, src/lib.rs
The feature for never type had to be added. I think this has changed recently. ~The const saturating int methods feature is no longer needed in current nightlies.~
Signed-off-by: Peak Morgana <pm@pm.me>
=> Fix never_type with nightly

examples/curl-easy-report.rs, examples/curl-easy2-report.rs, examples/reqwest-report.rs, src/transaction.rs, src/usage.rs
Hi, since it is mentioned in comments I implemented usages module without the cloning. Feel free to ignore if not useful. I exposed an inner tuple struct and added methods to access it but could be kept private. Then I changed a few tests and the example code.
I think it is interesting to do this for a `no_std` version, do you plan to support it?
=> Use references in usage

CHANGELOG.md
Release 0.4.0 with the changes in `Usage` and the example code fixes to avoid deprecation warnings.
=> CHANGELOG: release 0.4.0

Cargo.toml, examples/reqwest-report.rs, src/http/request/http.rs, src/http/request/reqwest.rs
The two need to move at once since reqwest uses some HTTP types. Additionally, the async client is now the default, and the sync one moved under the `blocking` namespace.
Another minor change we needed to do was using `serde_json` explicitly to parse the response without consuming it in the Reqwest example.
=> http,reqwest: update to http 0.2 and reqwest 0.10

Cargo.toml, src/encoding.rs
We have defined the corresponding encoding sets used in version 1. The initial `QUERY_ENCODE_SET` is based on the [upgrading guide](https://github.com/servo/rust-url/blob/f091d2b45b79958f9a40e2b98b844f75df6723de/UPGRADING.md#upgrading-from-percent-encoding-1x-to-2x) for the updated crate.
=> Cargo.toml,src/encoding: update to percent_encoding 2

build.rs, src/http/parameters.rs, src/lib.rs, src/timestamp.rs
Nightlies are currently breaking because we call `feature(...)` on them for a feature that was just stabilised.
With this PR we fix nightlies _and_ we also enable that feature for versions of Rust 1.47.0+ while keeping previous versions working.
=> Use a flag-based system for features and fix nightly

CHANGELOG.md, Cargo.toml
This release is mostly about fixing the library to work on nightly compilers.
=> Release 0.6.1

Cargo.toml, src/api_call.rs, src/application.rs, src/credentials.rs, src/extensions/extension.rs, src/extensions/list.rs, src/http.rs, src/http/parameters.rs, src/http/request.rs, src/http/request/curl.rs, src/http/request/curl/easy.rs, src/http/request/curl/easy2.rs, src/http/request/http_types.rs, src/http/request/reqwest.rs, src/lib.rs, src/response.rs, src/service.rs, src/transaction.rs, src/usage.rs, src/user.rs
This adds support for `#[no_std]` assuming there is an allocator.
Errors are handled via `anyhow` because it's pretty close to `Box<dyn Error>` and has a `no_std` mode.
Some code using `HashMap` has been changed to use `BTreeMap` because the exact implementation has never been important and it allows us to not depend on another crate in no_std.
=> #[no_std] compat

Cargo.toml, README.md, build.rs, src/http/parameters.rs, src/http/request/http_types.rs, src/lib.rs, src/util.rs, src/util/compat.rs, src/util/compat/features.rs, src/util/compat/features/inner_deref.rs, src/util/compat/features/iterator_fold_self.rs, src/util/compat/features/never.rs, src/util/compat/macros.rs
With this PR the following command compiles just fine:
> cargo +1.40.0 build --no-default-features --features std,http-types,xml-response
This currently pulls in full functionality without `curl` and `reqwest` integrations (which will require a higher rustc version if used).
Going lower than 1.40.0 is possible but would require forking several dependencies to fix incompatibilities or disabling useful non-integration features like `xml-response`.
This PR uses a fork of `autocfg` that can test for features and improves a lot on the existing `build.rs` program by testing for paths/types/features rather than relying on hardcoded compiler channel and version databases, which prove tricky to scale. It's not likely that the fork will make it back to the upstream `autocfg` as is, but we won't be …
=> Minimum Supported Rust Version 1.40.0+

src/response.rs
Indexing a map via `[]` will panic when a key is not found, and we do this when deserializing the hierarchy of metrics in a response. Return instead a `serde` error.
=> response: avoid panicking when parsing metrics hierarchy

src/application.rs, src/credentials.rs, src/http.rs, src/response.rs
This becomes useful mainly for exposing these types across FFI without
surprising effects.
=> misc: add repr(transparent) to more unit structs

src/api_call.rs, src/http/request.rs, src/http/request/http_types.rs, src/transaction.rs
Some structs have multiple lifetimes to make all of them independent from
each other. We have covariant lifetimes and I think having a single
lifetime may be enough to simplify code and cause no regressions.
So far the examples run unmodified but I have to check other users.
=> misc: simplify lifetimes

build.rs, src/api_call.rs, src/application.rs, src/credentials.rs, src/extensions/extension.rs, src/extensions/list.rs, src/http.rs, src/http/parameters.rs, src/lib.rs, src/response.rs, src/response/app_keys_list.rs, src/response/metrics_hierarchy.rs, src/service.rs, src/transaction.rs, src/usage.rs, src/user.rs
This implements support for the [`app_keys_list` extension](https://github.com/3scale/apisonator/issues/282) and refactors the `response` module to reduce complexity by extracting the support for metric hierarchies to its own module and fixes the following bugs:
1. The `Authorization` enum incorrectly tagged Auth* calls that failed (NB: **not denied**, but failed) as denied.
2. The enum above did not contain the authorization status due to assuming that not having an error meant a call was authorized.
3. Some authorization calls might have no usage reports because of no limits set, but the logic required usage_reports to exist.
This PR also introduces a standardization of opt-in built-in traits (ie. `Debug, Clone, PartialEq, Eq` are the usual ones) in most places to help with usability …
=> Support app_keys_list extension

src/response.rs
After parsing an 'authorize' response from 3scale, there was no way to access fields inside the `OkAuthorization` struct. In this PR, I have added getters to give access to these fields as references. Please let me know if there is a change required.
=> Add getters for AuthorizationStatus and AuthorizationError Structs

src/extensions/extension.rs, src/response.rs, src/response/app_keys_list.rs
This PR fixes the list_app_keys extension naming issue inside threescalers. Fixes #92
=> list_app_keys extension naming fixed

Cargo.toml, build.rs
Since crates.io cannot publish crates that refer to git repositories, we cannot release using our fork of autocfg that enables feature detection. This means we either a) wait for autocfg to land feature detection, b) release a new crate with this modification, or c) vendor our fork.
Out of these, a) might not happen or not happen soon, b) pollutes the crates.io namespace in a way that feels not justified, and c) looks great because we can easily vendor autocfg inline, as it is pretty small.
So c).
=> Vendor our autocfg fork inline

src/lib.rs
This just enables clippy lints on the cargo manifest.
=> lib: enable clippy lints on cargo settings

src/response.rs
This makes `Period` resistant to Apisonator adding new periods (if ever?) by creating its own version of non-exhaustiveness (ie. adding an `Other` variant).
=> response: make Period non exhaustive by adding Other to avoid failure with unknown variants

src/extensions/list.rs, src/response.rs, src/response/usage_report.rs
Add helpers for `Authorization` to query and extract its contents, and add a helper to `Extension::List` to easily enable the `list_app_keys` extension.
=> response,extensions: add useful helpers to Authorization and Extension::List

Cargo.toml, src/http.rs, src/http/mapping_rule.rs, src/http/mapping_rule/escaping.rs, src/http/mapping_rule/method.rs, src/http/mapping_rule/serde_impl.rs, src/util.rs, src/util/string.rs
This introduces optional features useful for proxies:
- rest-mappings
- rest-mappings-serde
Compatibility: while these do not enforce the "std" feature, they
currently end up requiring it effectively because of the regular
expression engine requirements.
This implements the matching of HTTP (REST) mapping rules via inspection
of the HTTP method, path and query string.
The current implementation is just an approximation of what Apicast is
currently doing. There are a few reasons for this, not the least that
the documentation underspecifies this functionality and that Apicast
itself just passes down unchecked contents to its PCRE-based regular
expression engine.
In particular, this specification allows users to specify:
- Method: the HTTP verb literal string or the string "any" …
=> Mapping rules implementation
